### ISSUE TITLE
Change name of primary key field that is automatically generated

### ISSUE THREAD

**Issue by filipeteles** [ContinuumIO/datashape#138] opened 2015-04-06 04:09 UTC
Is it possible to change it from the default 'id', to something else?

**Comment by mrocklin** [comment] 2015-04-06 14:50
In what context is datashape generating a primary key?  Is it possible that this is happening within your database?

**Comment by cpcloud** [comment] 2015-04-07 17:08
To be clear, datashape knows nothing about primary keys so we don't generate any default names.

**Comment by cpcloud** [comment] 2015-04-17 16:01
closing as not a bug

**Closed by cpcloud** 2015-04-17 16:01 UTC
Labels: question
